version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yaeshora
      POSTGRES_DB: elexplorador
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:yaeshora@db:5432/elexplorador
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: